language: java
sudo: false
install: true

jdk:
  - openjdk11

addons: 
  sonarcloud:
      organization: "uniqueck-github"
      token:
        secure: $SONAR_TOKEN
  apt:
    packages:
      - graphviz


jobs:   
  include:   
    - stage: build and test
      if: NOT branch = develop OR type = pull_request 
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=uniqueck_test-report-generator

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
